package com.maxlananas.fawebim.core.command;

/**
 * The signature of every brush, generated by
 * {@code scripts/generate_command_tables.py} from the WorldEdit and FAWE
 * brush declarations.
 *
 * <p>Each record is {@code name, aliases, arguments, switches, valueFlags,
 * description}: {@code arguments} is a list of {@code name, default} pairs
 * in the order FAWE declares them, {@code switches} are the {@code -x}
 * flags and {@code valueFlags} are the {@code -x <value>} options.</p>
 *
 * <p>Do not edit by hand: re-run the script after changing the command set.</p>
 */
public final class BrushTable {

    private BrushTable() {
    }

    /** The signature of a brush, by name or alias, or null when it is unknown. */
    public static String[] byName(String name) {
        if (name == null) {
            return null;
        }
        for (String[] row : BRUSHES) {
            if (row[0].equals(name)) {
                return row;
            }
            for (String alias : row[1].split(",")) {
                if (!alias.isEmpty() && alias.equals(name)) {
                    return row;
                }
            }
        }
        return null;
    }

    public static final String[][] BRUSHES = {
            {"biome", "", "shape=|radius=5|biomeType=", "c", "", "Biome brush, sets biomes in the area"},
            {"blendball", "bb,blend", "radius=5|minFreqDiff=1", "a", "m", "Smooths and blends terrain"},
            {"butcher", "kill", "radius=5", "p,n,g,a,b,t,f,r,w", "", "Butcher brush, kills mobs within a radius"},
            {"catenary", "cat,gravityline,saggedline", "fill=|lengthFactor=1.2|radius=0", "h,s,d", "", "Create a hanging line between two points"},
            {"circle", "", "fill=|radius=5|filled=false", "", "", "Creates a circle, which revolves around your facing direction"},
            {"cliff", "flatcylinder", "radius=5|image=|rotation=0|yscale=1", "r,l,s", "", "Cliff brush"},
            {"clipboard", "copy", "", "a,o,e,b,r,v", "m", "Paste your clipboard at the brush location. Includes any transforms."},
            {"command", "cmd", "radius=|input=", "h", "", "Command brush"},
            {"copypaste", "cp,copypasta", "radius=5", "r,a", "", "Copy Paste brush"},
            {"cylinder", "cyl,c", "pattern=|radius=2|height=1|thickness=0", "h", "", "Choose the cylinder brush"},
            {"deform", "", "shape=|radius=5|expression=y-=0.2", "r,o", "", "Deform brush, applies an expression to an area"},
            {"dilate", "", "brushSize=5", "", "", "Dilate preset for morph brush, dilates blocks in the area"},
            {"erode", "", "radius=5|erodefaces=2|erodeRec=1|fillFaces=5|fillRec=1", "", "", "Erodes terrain"},
            {"extinguish", "ex", "radius=5", "", "", "Shortcut fire extinguisher brush"},
            {"feature", "", "shape=|radius=5|density=5|type=", "", "", "Feature brush, paints Minecraft generation features"},
            {"flatten", "flatmap,flat", "radius=5|image=|rotation=0|yscale=1", "r,l,s", "", "This brush raises or lowers land towards the clicked point"},
            {"forest", "", "shape=|radius=5|density=20|type=", "", "", "Plant trees"},
            {"gravity", "grav", "radius=5", "h", "h", "Gravity brush, simulates the effect of gravity"},
            {"height", "", "radius=5|yscale=1|image=|rotation=0", "r,l,s", "", "Raise or lower terrain using a heightmap"},
            {"heightmap", "", "imageName=|radius=5|intensity=5", "e,f,r", "", "Heightmap brush, raises or lowers terrain using an image heightmap"},
            {"image", "", "?=|radius=5|yscale=1", "a,f", "", "Use a height map to paint a surface"},
            {"item", "", "item=|direction=up", "", "", "Use an item"},
            {"layer", "", "radius=|patternLayers=", "", "", "Replaces terrain with a layer."},
            {"line", "l", "fill=|radius=0", "h,s,f", "", "Create lines"},
            {"lower", "", "shape=|radius=5", "", "", "Lower brush, lower all blocks by one"},
            {"morph", "", "brushSize=5|minErodeFaces=3|numErodeIterations=1|minDilateFaces=3|numDilateIterations=1", "", "", "Morph brush, morphs blocks in the area"},
            {"populateschematic", "populateschem,popschem,pschem,ps", "clipboardStr=|mask=|radius=30|density=50", "r", "", "Scatter a schematic on a surface"},
            {"pull", "", "radius=5|erodefaces=6|erodeRec=0|fillFaces=1|fillRec=1", "", "", "Pull terrain towards you"},
            {"raise", "", "shape=|radius=5", "", "", "Raise brush, raise all blocks by one"},
            {"recursive", "recurse,r", "fill=|radius=5", "d", "", "Set all connected blocks"},
            {"rock", "blob", "fill=|radius=10|sphericity=100|frequency=30|amplitude=50", "", "", "Creates a distorted sphere"},
            {"scatter", "", "fill=|radius=5|points=5|distance=1", "o", "", "Scatter a pattern on a surface"},
            {"scattercommand", "scattercmd,scmd,scommand", "radius=|points=1|distance=1|commandStr=", "p", "", "Run commands at random points on a surface"},
            {"set", "", "shape=|radius=5|pattern=", "", "", "Place a block"},
            {"shatter", "partition,split", "fill=|radius=10|count=10", "", "", "Creates random lines to break the terrain into pieces"},
            {"smooth", "", "radius=2|iterations=4|mask=", "", "", "Choose the terrain softener brush"},
            {"snow", "", "shape=|radius=5", "s", "", "Snow brush, sets snow in the area"},
            {"snowsmooth", "", "radius=2|iterations=1", "", "l,m", "Choose the snow terrain softener brush"},
            {"sphere", "s", "pattern=|radius=2", "h,f", "", "Choose the sphere brush"},
            {"splatter", "splat", "fill=|radius=5|points=1|recursion=5|solid=true", "", "", "Splatter a pattern on a surface"},
            {"spline", "spl,curve", "fill=|radius=25", "", "", "Join multiple objects together in a curve"},
            {"stencil", "", "fill=|radius=5|image=|rotation=0|yscale=1", "w,r", "", "Use a height map to paint a surface"},
            {"structure", "", "shape=|radius=5|density=5|type=", "", "", "Structure brush, paints Minecraft generation structures"},
            {"surface", "surf", "fill=|radius=5", "", "", "Use a height map to paint a surface"},
            {"surfacespline", "sspline,sspl", "fill=|radius=0|tension=0|bias=0|continuity=0|quality=10", "", "", "Draws a spline (curved line) on the surface"},
            {"sweep", "sw,vaesweep", "copies=-1", "", "", "Sweep your clipboard content along a curve"},
    };
}
