package com.maxlananas.fawebim.core.command;

/**
 * Alias routes generated by {@code scripts/generate_command_tables.py}.
 *
 * <p>WorldEdit declares a command once and gives it several spellings, and
 * declares brush, tool, schematic, snapshot and super-pickaxe sub-commands
 * inside their container. Each pair is {@code spelling}, {@code command}:
 * the spelling runs the command that already implements the behaviour, so no
 * duplicate implementation is needed for names such as {@code 0} ({@code /air})
 * or {@code blob} ({@code /brush rock}).</p>
 *
 * <p>Do not edit by hand: re-run the script after changing the command set.</p>
 */
final class SubCommandTable {

    private SubCommandTable() {
    }

    static final String[] PAIRS = {
            "rock", "blob",
            "middle", "//center",
            "mirror", "//flip",
            "globalsourcemask", "gsmask",
            "mv", "//move",
            "pa", "//paste",
            "rep", "//replace",
            "select", "wer",
            "biomels", "//biomelist",
            "listbiomes", "//biomelist",
            "/brush bb", "/brush blendball",
            "/brush blend", "/brush blendball",
            "/brush kill", "/brush butcher",
            "/brush cat", "/brush catenary",
            "/brush gravityline", "/brush catenary",
            "/brush saggedline", "/brush catenary",
            "cc", "//clearclipboard",
            "clearclip", "//clearclipboard",
            "/brush cmd", "/brush command",
            "/brush cp", "/brush copypaste",
            "/brush copypasta", "/brush copypaste",
            "/brush cyl", "/brush cylinder",
            "/brush c", "/brush cylinder",
            "/brush ex", "/brush extinguish",
            "ext", "//extinguish",
            "/brush flatmap", "/brush flatten",
            "/brush flat", "/brush flatten",
            "/brush grav", "/brush gravity",
            "/brush l", "/brush line",
            "/tool mat", "/tool material",
            "/tool pattern", "/tool material",
            "/brush populateschem", "/brush populateschematic",
            "/brush popschem", "/brush populateschematic",
            "/brush pschem", "/brush populateschematic",
            "/brush ps", "/brush populateschematic",
            "/brush r", "/brush recursive",
            "/brush scattercmd", "/brush scattercommand",
            "/brush scmd", "/brush scattercommand",
            "/brush scommand", "/brush scattercommand",
            "/brush partition", "/brush shatter",
            "/brush split", "/brush shatter",
            "/brush spl", "/brush spline",
            "/brush curve", "/brush spline",
            "/brush surf", "/brush surface",
            "/brush sspline", "/brush surfacespline",
            "/brush sspl", "/brush surfacespline",
            "/brush sw", "/brush sweep",
            "/brush vaesweep", "/brush sweep",
            "/tool tarmask", "/tool tracemask",
            "/tool tm", "/tool tracemask",
            "/tool targetmask", "/tool tracemask",
            "/brush copy", "/brush clipboard",
            "/brush splat", "/brush splatter",
    };
}
