package com.fawebutinmods.core.command;

/**
 * Alias table generated by {@code scripts/generate_alias_table.py}.
 *
 * <p>Each pair is {@code alias}, {@code canonical command}: WorldEdit declares
 * aliases next to the command they belong to, so a stub that is really an alias
 * of a finished command is wired to it instead of staying a stub.</p>
 *
 * <p>Do not edit by hand: re-run the script after changing the command set.</p>
 */
final class AliasTable {

    private AliasTable() {
    }

    static final String[] PAIRS = {
            "//asc", "//ascend",
            "//biomels", "//biomelist",
            "//c", "//cyl",
            "//clipboard", "//copy",
            "//cylinder", "//cyl",
            "//ext", "//extinguish",
            "//l", "//line",
            "//listbiomes", "//biomelist",
            "//m", "//move",
            "//middle", "//center",
            "//mirror", "//flip",
            "//mv", "//move",
            "//pa", "//paste",
            "//rep", "//replace",
            "//s", "//sphere",
            "//spl", "//curve",
            "//spline", "//curve",
            "//ver", "//version",
            "/deselect", "//sel",
            "/distribution", "//distr",
            "/ex", "//extinguish",
            "/g", "//generate",
            "/gen", "//generate",
            "/j", "//jumpto",
            "/p", "//paste",
            "/r", "//replace",
            "/re", "//replace",
    };
}
