package com.fawebutinmods.core.command;

import com.fawebutinmods.core.util.Msg;

/**
 * Registers every remaining WorldEdit/FAWE command name.
 *
 * <p>The list below is the complete command surface extracted from WorldEdit
 * 7.3.17 and FastAsyncWorldEdit: no name is missing, so the mod always exposes
 * the full {@code //} and {@code /} command set. Commands whose implementation
 * is not finished in this build answer with an explicit "not implemented yet"
 * message and are marked in {@code docs/COMMANDS.md}, which keeps the surface
 * complete while the remaining behaviours are ported.</p>
 */
final class Stubs {

    private Stubs() {
    }

    private static final String[] REMAINING = {
            "//after", "Choose the nearest snapshot after a date",
            "//air", "Sets all the blocks in the region to air",
            "//all", "List both public and private schematics",
            "//area", "Enable the area super pickaxe pickaxe mode",
            "//asc", "Go up a floor",
            "//ascend", "Go up a floor",
            "//bb", "Smooths and blends terrain",
            "//before", "Choose the nearest snapshot before a date",
            "//biome", "Biome brush, sets biomes in the area",
            "//biomeinfo", "Get the biome of the targeted block.",
            "//biomelist", "Gets all biomes available.",
            "//biomels", "Gets all biomes available.",
            "//blend", "Smooths and blends terrain",
            "//blendball", "Smooths and blends terrain",
            "//blob", "Creates a distorted sphere",
            "//butcher", "Butcher brush, kills mobs within a radius",
            "//c", "Choose the cylinder brush",
            "//calc", "Evaluate a mathematical expression",
            "//calculate", "Evaluate a mathematical expression",
            "//cancel", "Cancel your current command",
            "//cat", "Create a hanging line between two points",
            "//catenary", "Create a hanging line between two points",
            "//caves", "Generates a cave network",
            "//cc", "Clear your clipboard",
            "//ceil", "Go to the ceiling",
            "//ceiling", "Go to the ceiling",
            "//center", "Set the center block(s)",
            "//chunk", "Set the selection to your current chunk.",
            "//chunkinfo", "Get information about the chunk you're inside",
            "//circle", "Creates a circle, which revolves around your facing direction",
            "//clear", "Clear the chunks in a selection (delete without defrag)",
            "//clearclip", "Clear your clipboard",
            "//clearclipboard", "Clear your clipboard",
            "//clearhistory", "Clear your history",
            "//cliff", "Cliff brush",
            "//clipboard", "Paste your clipboard at the brush location. Includes any transforms.",
            "//cmd", "Command brush",
            "//command", "Command brush",
            "//cone", "Generates a cone.",
            "//confirm", "Confirm a command",
            "//contract", "Contract the selection area",
            "//copy", "Copy the selection to the clipboard",
            "//copypasta", "Copy Paste brush",
            "//copypaste", "Copy Paste brush",
            "//count", "Counts the number of blocks matching a mask",
            "//countall", "Count all blocks in a world",
            "//cp", "Copy Paste brush",
            "//cs", "Execute a CraftScript",
            "//cui", "Complete CUI handshake (internal usage)",
            "//curve", "Draws a spline through selected points",
            "//cut", "Cut the selection to the clipboard",
            "//cycler", "Block data cycler tool",
            "//cyl", "Generates a cylinder.",
            "//cylinder", "Choose the cylinder brush",
            "//d", "Delete a saved schematic",
            "//debugfixroads", "debug - do not use",
            "//debugpaste", "Writes a report of latest.log, config.yml, worldedit-config.yml, strings.json to https://athion.net/ISPaster/p",
            "//deform", "Deforms a selected region with an expression",
            "//delallunclaimed", "Delete all chunks which haven't been occupied",
            "//delchunks", "Delete chunks that your selection includes",
            "//delete", "Delete a saved schematic",
            "//deletealloldregions", "Delete regions which haven't been accessed in a certain amount of time",
            "//deleteallunclaimed", "Delete all chunks which haven't been occupied",
            "//deleteallunvisited", "Delete all chunks which haven't been occupied",
            "//deletebiomechunks", "Delete chunks matching a specific biome",
            "//deleteunclaimed", "Delete all chunks which haven't been occupied",
            "//deloldreg", "Delete regions which haven't been accessed in a certain amount of time",
            "//deltree", "Floating tree remover tool",
            "//delunvisited", "Delete all chunks which haven't been occupied",
            "//desc", "Go down a floor",
            "//descend", "Go down a floor",
            "//desel", "Choose a region selector",
            "//deselect", "Choose a region selector",
            "//dilate", "Dilate preset for morph brush, dilates blocks in the area",
            "//distr", "Get the distribution of blocks in the selection",
            "//distribution", "View block distribution for an edit",
            "//download", "Downloads your clipboard through the configured web interface",
            "//drain", "Drain a pool",
            "//drawsel", "Toggle drawing the current selection",
            "//erode", "Erodes terrain",
            "//eval", "Evaluate a mathematical expression",
            "//evaluate", "Evaluate a mathematical expression",
            "//ex", "Shortcut fire extinguisher brush",
            "//ext", "Extinguish nearby fire",
            "//extinguish", "Shortcut fire extinguisher brush",
            "//f", "List available formats",
            "//faces", "Build the walls, ceiling, and floor of a selection",
            "//fall", "Have the blocks in the selection fall",
            "//farwand", "Wand at a distance tool",
            "//fast", "Toggle fast mode",
            "//fcancel", "Cancel your current command",
            "//feature", "Feature brush, paints Minecraft generation features",
            "//featureplacer", "Feature placer tool",
            "//featuretool", "Feature placer tool",
            "//fill", "Fill a hole",
            "//fillr", "Fill a hole recursively",
            "//find", "Find nearby edits",
            "//fixblocks", " 'Fixes ' all blocks in the region to the correct shape/connections based on surrounding blocks",
            "//fixconnect", " 'Fixes ' all blocks in the region to the correct shape/connections based on surrounding blocks",
            "//fixlava", "Fix lava to be stationary",
            "//fixlighting", "Get the light at a position",
            "//fixwater", "Fix water to be stationary",
            "//flat", "This brush raises or lowers land towards the clicked point",
            "//flatcylinder", "Cliff brush",
            "//flatmap", "This brush raises or lowers land towards the clicked point",
            "//flatten", "This brush raises or lowers land towards the clicked point",
            "//flip", "Flip the contents of the clipboard across the origin",
            "//flood", "Flood fill tool",
            "//floodfill", "Flood fill tool",
            "//flora", "Make flora within the region",
            "//forest", "Make a forest within the region",
            "//forestgen", "Generate a forest",
            "//formats", "List available formats",
            "//g", "Generates a shape according to a formula.",
            "//gb", "Sets biome according to a formula.",
            "//gen", "Generates a shape according to a formula.",
            "//genbiome", "Sets biome according to a formula.",
            "//generate", "Generates a shape according to a formula.",
            "//generatebiome", "Sets biome according to a formula.",
            "//global", "List public schematics",
            "//globalsourcemask", "Set the global source mask",
            "//gmask", "Set the global mask",
            "//grav", "Gravity brush, simulates the effect of gravity",
            "//gravity", "Gravity brush, simulates the effect of gravity",
            "//gravityline", "Create a hanging line between two points",
            "//green", "Converts dirt to grass blocks in the area",
            "//gsmask", "Set the global source mask",
            "//gtexture", "Set the global mask",
            "//gtransform", "Set the global transform",
            "//hcyl", "Generates a hollow cylinder.",
            "//height", "Raise or lower terrain using a heightmap",
            "//heightmap", "Raise or lower terrain using a heightmap",
            "//heightmapinterface", "Generate the heightmap interface: https://github.com/IntellectualSites/HeightMap",
            "//help", "Displays help for WorldEdit commands",
            "//hmi", "Generate the heightmap interface: https://github.com/IntellectualSites/HeightMap",
            "//hollow", "Hollows out the object contained in this selection",
            "//hpos1", "Set position 1 to targeted block",
            "//hpos2", "Set position 2 to targeted block",
            "//hpyramid", "Generate a hollow pyramid",
            "//hsphere", "Generates a hollow sphere.",
            "//image", "Generate an image",
            "//img", "Generate an image",
            "//import", "Import history into the database",
            "//info", "Summarize an edit",
            "//inset", "Inset the selection area",
            "//inspect", "Find nearby edits",
            "//item", "Use an item",
            "//j", "Teleport to a location",
            "//jumpto", "Teleport to a location",
            "//kill", "Butcher brush, kills mobs within a radius",
            "//l", "Create lines",
            "//lay", "Set the top block in the region",
            "//layer", "Replaces terrain with a layer.",
            "//lazycopy", "Lazily copy the selection to the clipboard",
            "//lazycut", "Lazily cut the selection to the clipboard",
            "//limit", "Modify block change limit",
            "//line", "Draws line segments between cuboid selection corners or convex polyhedral selection vertices",
            "//list", "List your history",
            "//listbiomes", "Gets all biomes available.",
            "//listbrush", "List saved brushes",
            "//listchunks", "List chunks that your selection includes",
            "//listformats", "List available formats",
            "//load", "Load a schematic into your clipboard",
            "//loadall", "Load multiple clipboards (paste will randomly choose one)",
            "//loadbrush", "Load a brush",
            "//local", "List your personal schematics",
            "//lower", "Lower brush, lower all blocks by one",
            "//lrbuild", "Long-range building tool",
            "//ls", "List saved schematics",
            "//m", "Move your loaded schematic",
            "//macro", "Generate or run a macro",
            "//mask", "Set the brush destination mask",
            "//masks", "View help about masks",
            "//mat", "Set the brush material",
            "//material", "Set the brush material",
            "//me", "List your personal schematics",
            "//middle", "Set the center block(s)",
            "//mine", "List your personal schematics",
            "//mirror", "Flip the contents of the clipboard across the origin",
            "//morph", "Morph brush, morphs blocks in the area",
            "//move", "Move the contents of the selection",
            "//mv", "Move the contents of the selection",
            "//naturalize", "3 layers of dirt on top then rock below",
            "//navwand", "Navigation wand tool",
            "//nbtinfo", "View nbt info for a block",
            "//near", "Find nearby edits",
            "//none", "Unbind a bound tool from your current item",
            "//ore", "Generates ores",
            "//ores", "Generates ores",
            "//outline", "Build the walls, ceiling, and floor of a selection",
            "//outset", "Outset the selection area",
            "//overlay", "Set a block on top of blocks in the region",
            "//p", "Paste the clipboard's contents",
            "//pa", "Paste the clipboard's contents",
            "//partition", "Creates random lines to break the terrain into pieces",
            "//paste", "Paste the clipboard's contents",
            "//pattern", "Set the brush material",
            "//perf", "Toggle side effects for performance",
            "//place", "Place the clipboard's contents without applying transformations (e.g. rotate)",
            "//placement", "Select which placement to use",
            "//popschem", "Scatter a schematic on a surface",
            "//populateschem", "Scatter a schematic on a surface",
            "//populateschematic", "Scatter a schematic on a surface",
            "//pos", "Set positions",
            "//pos1", "Set position 1",
            "//pos2", "Set position 2",
            "//preplace", "Replace all blocks in the selection with a pattern",
            "//primary", "Set the right click brush",
            "//private", "List your personal schematics",
            "//ps", "Scatter a schematic on a surface",
            "//pschem", "Scatter a schematic on a surface",
            "//public", "List public schematics",
            "//pull", "Pull terrain towards you",
            "//pumpkins", "Generate pumpkin patches",
            "//pyramid", "Generate a filled pyramid",
            "//r", "Set all connected blocks",
            "//raise", "Raise brush, raise all blocks by one",
            "//range", "Set the brush range",
            "//re", "Replace all blocks in the selection with another",
            "//rea", "Replace all blocks in the selection with another",
            "//reap", "Replace all blocks in the selection with another",
            "//recur", "Enable the recursive super pickaxe pickaxe mode",
            "//recurse", "Set all connected blocks",
            "//recursive", "Set all connected blocks",
            "//redo", "Redoes the last action (from history)",
            "//regen", "Regenerates the contents of the selection",
            "//registry", "Search through the given registry",
            "//reload", "Reload configuration and translations",
            "//rem", "Remove all entities of a type",
            "//remapall", "Remap the world between MCPE/PC values",
            "//rement", "Remove all entities of a type",
            "//remove", "Remove all entities of a type",
            "//removeabove", "Remove blocks above your head.",
            "//removebelow", "Remove blocks below you.",
            "//removelayers", "Removes matching chunk layers",
            "//removelighting", "Removing lighting in a selection",
            "//removenear", "Remove blocks near you.",
            "//reorder", "Sets the reorder mode of WorldEdit",
            "//rep", "Replace all blocks in the selection with another",
            "//repall", "Replace all blocks in the selection with another",
            "//repallpat", "Replace all blocks in the selection with another",
            "//repl", "Block replacer tool",
            "//replace", "Replace all blocks in the selection with another",
            "//replaceall", "Replace all blocks in the selection with another",
            "//replaceallpattern", "Replace all blocks in the selection with another",
            "//replacenear", "Replace nearby blocks",
            "//replacepattern", "Replace all blocks in the selection with a pattern",
            "//report", "Writes a report on WorldEdit",
            "//rerun", "Rerun edits",
            "//restore", "Rerun edits",
            "//rock", "Creates a distorted sphere",
            "//rollback", "Undo a specific edit. ",
            "//rotate", "Rotate the contents of the clipboard",
            "//rp", "Replace all blocks in the selection with a pattern",
            "//s", "Choose the sphere brush",
            "//saggedline", "Create a hanging line between two points",
            "//save", "Save your clipboard into a schematic file",
            "//savebrush", "Save your current brush",
            "//scatter", "Scatter a pattern on a surface",
            "//scattercmd", "Run commands at random points on a surface",
            "//scattercommand", "Run commands at random points on a surface",
            "//scmd", "Run commands at random points on a surface",
            "//scommand", "Run commands at random points on a surface",
            "//scroll", "Toggle between different target modes",
            "//search", "Find nearby edits",
            "//searchitem", "Search for an item",
            "//secondary", "Set the left click brush",
            "//sel", "Choose a region selector",
            "//select", "Select your current allowed region",
            "//selwand", "Selection wand tool",
            "//set", "Sets all the blocks in the region",
            "//setbiome", "Sets the biome of your current block or region.",
            "//setblocklight", "Set block lighting in a selection",
            "//setskylight", "Set sky lighting in a selection",
            "//share", "Share your clipboard as a schematic online",
            "//shatter", "Creates random lines to break the terrain into pieces",
            "//shift", "Shift the selection area",
            "//single", "Enable the single block super pickaxe mode",
            "//size", "Get information about the selection",
            "//smask", "Set the brush source mask",
            "//smooth", "Smooth the elevation in the selection",
            "//snow", "Snow brush, sets snow in the area",
            "//snowsmooth", "Smooth the elevation in the selection with snow layers",
            "//solve", "Evaluate a mathematical expression",
            "//sourcemask", "Set the brush source mask",
            "//sphere", "Generates a filled sphere.",
            "//spl", "Join multiple objects together in a curve",
            "//splat", "Choose the splatter brush",
            "//splatter", "Splatter a pattern on a surface",
            "//spline", "Join multiple objects together in a curve",
            "//split", "Creates random lines to break the terrain into pieces",
            "//sspl", "Draws a spline (curved line) on the surface",
            "//sspline", "Draws a spline (curved line) on the surface",
            "//stack", "Repeat the contents of the selection",
            "//stacker", "Block stacker tool",
            "//stencil", "Use a height map to paint a surface",
            "//structure", "Generate Minecraft structures",
            "//structureplacer", "Structure placer tool",
            "//structuretool", "Structure placer tool",
            "//summarize", "Summarize an edit",
            "//summary", "Summarize an edit",
            "//surf", "Use a height map to paint a surface",
            "//surface", "Use a height map to paint a surface",
            "//surfacespline", "Draws a spline (curved line) on the surface",
            "//sw", "Sweep your clipboard content along a curve",
            "//sweep", "Sweep your clipboard content along a curve",
            "//tar", "Toggle between different target modes",
            "//target", "Toggle between different target modes",
            "//targetmask", "Set the mask used to stop tool traces",
            "//targetoffset", "Set the targeting mask",
            "//tarmask", "Set the mask used to stop tool traces",
            "//test", "test region",
            "//thaw", "Thaws the area",
            "//threads", "Print all thread stacks",
            "//thru", "Pass through walls",
            "//timeout", "Modify evaluation timeout time.",
            "//tips", "Toggle FAWE tips",
            "//tm", "Set the mask used to stop tool traces",
            "//to", "Set the targeting mask",
            "//toggleeditwand", "Remind the user that the wand is now a tool and can be unbound with /tool none.",
            "//toggleplace", "Switch between your position and pos1 for placement",
            "//trace", "Toggles trace hook",
            "//tracemask", "Set the mask used to stop tool traces",
            "//transform", "Set the brush transform",
            "//transforms", "View help about transforms",
            "//tree", "Tree generator tool",
            "//trim", "Minimize the selection to encompass matching blocks",
            "//trimallair", "Trim all air in the world",
            "//trimallplots", "Trim chunks in a Plot World",
            "//tz", "Set your timezone for snapshots",
            "//undo", "Undoes the last action (from history)",
            "//unload", "Remove a clipboard from your multi-clipboard",
            "//unset", "Clear the chunks in a selection (delete without defrag)",
            "//unstuck", "Escape from being stuck inside a block",
            "//up", "Go upwards some distance",
            "//update", "Apply side effects to your selection",
            "//updateblocks", " 'Fixes ' all blocks in the region to the correct shape/connections based on surrounding blocks",
            "//use", "Choose a snapshot to use",
            "//vaesweep", "Sweep your clipboard content along a curve",
            "//ver", "Get the FAWE version",
            "//version", "Get the FAWE version",
            "//walls", "Build the four sides of the selection",
            "//wand", "Get the wand object",
            "//warwand", "Wand at a distance tool",
            "//watchdog", "Changes watchdog hook state.",
            "//wea", "Bypass region restrictions",
            "//weanywhere", "Bypass region restrictions",
            "//wer", "Select your current allowed region",
            "//world", "Sets the world override",
            "//worldeditanywhere", "Bypass region restrictions",
            "//worldeditregion", "Select your current allowed region",
            "/after", "Choose the nearest snapshot after a date",
            "/air", "Sets all the blocks in the region to air",
            "/all", "List both public and private schematics",
            "/area", "Enable the area super pickaxe pickaxe mode",
            "/asc", "Go up a floor",
            "/ascend", "Go up a floor",
            "/bb", "Smooths and blends terrain",
            "/before", "Choose the nearest snapshot before a date",
            "/biome", "Biome brush, sets biomes in the area",
            "/biomeinfo", "Get the biome of the targeted block.",
            "/biomelist", "Gets all biomes available.",
            "/biomels", "Gets all biomes available.",
            "/blend", "Smooths and blends terrain",
            "/blendball", "Smooths and blends terrain",
            "/blob", "Creates a distorted sphere",
            "/butcher", "Butcher brush, kills mobs within a radius",
            "/c", "Choose the cylinder brush",
            "/calc", "Evaluate a mathematical expression",
            "/calculate", "Evaluate a mathematical expression",
            "/cancel", "Cancel your current command",
            "/cat", "Create a hanging line between two points",
            "/catenary", "Create a hanging line between two points",
            "/caves", "Generates a cave network",
            "/cc", "Clear your clipboard",
            "/ceil", "Go to the ceiling",
            "/ceiling", "Go to the ceiling",
            "/center", "Set the center block(s)",
            "/chunk", "Set the selection to your current chunk.",
            "/chunkinfo", "Get information about the chunk you're inside",
            "/circle", "Creates a circle, which revolves around your facing direction",
            "/clear", "Clear the chunks in a selection (delete without defrag)",
            "/clearclip", "Clear your clipboard",
            "/clearclipboard", "Clear your clipboard",
            "/clearhistory", "Clear your history",
            "/cliff", "Cliff brush",
            "/clipboard", "Paste your clipboard at the brush location. Includes any transforms.",
            "/cmd", "Command brush",
            "/command", "Command brush",
            "/cone", "Generates a cone.",
            "/confirm", "Confirm a command",
            "/contract", "Contract the selection area",
            "/copy", "Copy the selection to the clipboard",
            "/copypasta", "Copy Paste brush",
            "/copypaste", "Copy Paste brush",
            "/count", "Counts the number of blocks matching a mask",
            "/countall", "Count all blocks in a world",
            "/cp", "Copy Paste brush",
            "/cs", "Execute a CraftScript",
            "/cui", "Complete CUI handshake (internal usage)",
            "/curve", "Draws a spline through selected points",
            "/cut", "Cut the selection to the clipboard",
            "/cycler", "Block data cycler tool",
            "/cyl", "Generates a cylinder.",
            "/cylinder", "Choose the cylinder brush",
            "/d", "Delete a saved schematic",
            "/debugfixroads", "debug - do not use",
            "/debugpaste", "Writes a report of latest.log, config.yml, worldedit-config.yml, strings.json to https://athion.net/ISPaster/p",
            "/deform", "Deforms a selected region with an expression",
            "/delallunclaimed", "Delete all chunks which haven't been occupied",
            "/delchunks", "Delete chunks that your selection includes",
            "/delete", "Delete a saved schematic",
            "/deletealloldregions", "Delete regions which haven't been accessed in a certain amount of time",
            "/deleteallunclaimed", "Delete all chunks which haven't been occupied",
            "/deleteallunvisited", "Delete all chunks which haven't been occupied",
            "/deletebiomechunks", "Delete chunks matching a specific biome",
            "/deleteunclaimed", "Delete all chunks which haven't been occupied",
            "/deloldreg", "Delete regions which haven't been accessed in a certain amount of time",
            "/deltree", "Floating tree remover tool",
            "/delunvisited", "Delete all chunks which haven't been occupied",
            "/desc", "Go down a floor",
            "/descend", "Go down a floor",
            "/desel", "Choose a region selector",
            "/deselect", "Choose a region selector",
            "/dilate", "Dilate preset for morph brush, dilates blocks in the area",
            "/distr", "Get the distribution of blocks in the selection",
            "/distribution", "View block distribution for an edit",
            "/download", "Downloads your clipboard through the configured web interface",
            "/drain", "Drain a pool",
            "/drawsel", "Toggle drawing the current selection",
            "/erode", "Erodes terrain",
            "/eval", "Evaluate a mathematical expression",
            "/evaluate", "Evaluate a mathematical expression",
            "/ex", "Shortcut fire extinguisher brush",
            "/ext", "Extinguish nearby fire",
            "/extinguish", "Shortcut fire extinguisher brush",
            "/f", "List available formats",
            "/faces", "Build the walls, ceiling, and floor of a selection",
            "/fall", "Have the blocks in the selection fall",
            "/farwand", "Wand at a distance tool",
            "/fast", "Toggle fast mode",
            "/fcancel", "Cancel your current command",
            "/feature", "Feature brush, paints Minecraft generation features",
            "/featureplacer", "Feature placer tool",
            "/featuretool", "Feature placer tool",
            "/fill", "Fill a hole",
            "/fillr", "Fill a hole recursively",
            "/find", "Find nearby edits",
            "/fixblocks", " 'Fixes ' all blocks in the region to the correct shape/connections based on surrounding blocks",
            "/fixconnect", " 'Fixes ' all blocks in the region to the correct shape/connections based on surrounding blocks",
            "/fixlava", "Fix lava to be stationary",
            "/fixlighting", "Get the light at a position",
            "/fixwater", "Fix water to be stationary",
            "/flat", "This brush raises or lowers land towards the clicked point",
            "/flatcylinder", "Cliff brush",
            "/flatmap", "This brush raises or lowers land towards the clicked point",
            "/flatten", "This brush raises or lowers land towards the clicked point",
            "/flip", "Flip the contents of the clipboard across the origin",
            "/flood", "Flood fill tool",
            "/floodfill", "Flood fill tool",
            "/flora", "Make flora within the region",
            "/forest", "Make a forest within the region",
            "/forestgen", "Generate a forest",
            "/formats", "List available formats",
            "/g", "Generates a shape according to a formula.",
            "/gb", "Sets biome according to a formula.",
            "/gen", "Generates a shape according to a formula.",
            "/genbiome", "Sets biome according to a formula.",
            "/generate", "Generates a shape according to a formula.",
            "/generatebiome", "Sets biome according to a formula.",
            "/global", "List public schematics",
            "/globalsourcemask", "Set the global source mask",
            "/gmask", "Set the global mask",
            "/grav", "Gravity brush, simulates the effect of gravity",
            "/gravity", "Gravity brush, simulates the effect of gravity",
            "/gravityline", "Create a hanging line between two points",
            "/green", "Converts dirt to grass blocks in the area",
            "/gsmask", "Set the global source mask",
            "/gtexture", "Set the global mask",
            "/gtransform", "Set the global transform",
            "/hcyl", "Generates a hollow cylinder.",
            "/height", "Raise or lower terrain using a heightmap",
            "/heightmap", "Raise or lower terrain using a heightmap",
            "/heightmapinterface", "Generate the heightmap interface: https://github.com/IntellectualSites/HeightMap",
            "/help", "Displays help for WorldEdit commands",
            "/hmi", "Generate the heightmap interface: https://github.com/IntellectualSites/HeightMap",
            "/hollow", "Hollows out the object contained in this selection",
            "/hpos1", "Set position 1 to targeted block",
            "/hpos2", "Set position 2 to targeted block",
            "/hpyramid", "Generate a hollow pyramid",
            "/hsphere", "Generates a hollow sphere.",
            "/image", "Generate an image",
            "/img", "Generate an image",
            "/import", "Import history into the database",
            "/info", "Summarize an edit",
            "/inset", "Inset the selection area",
            "/inspect", "Find nearby edits",
            "/item", "Use an item",
            "/j", "Teleport to a location",
            "/jumpto", "Teleport to a location",
            "/kill", "Butcher brush, kills mobs within a radius",
            "/l", "Create lines",
            "/lay", "Set the top block in the region",
            "/layer", "Replaces terrain with a layer.",
            "/lazycopy", "Lazily copy the selection to the clipboard",
            "/lazycut", "Lazily cut the selection to the clipboard",
            "/limit", "Modify block change limit",
            "/line", "Draws line segments between cuboid selection corners or convex polyhedral selection vertices",
            "/list", "List your history",
            "/listbiomes", "Gets all biomes available.",
            "/listbrush", "List saved brushes",
            "/listchunks", "List chunks that your selection includes",
            "/listformats", "List available formats",
            "/load", "Load a schematic into your clipboard",
            "/loadall", "Load multiple clipboards (paste will randomly choose one)",
            "/loadbrush", "Load a brush",
            "/local", "List your personal schematics",
            "/lower", "Lower brush, lower all blocks by one",
            "/lrbuild", "Long-range building tool",
            "/ls", "List saved schematics",
            "/m", "Move your loaded schematic",
            "/macro", "Generate or run a macro",
            "/mask", "Set the brush destination mask",
            "/masks", "View help about masks",
            "/mat", "Set the brush material",
            "/material", "Set the brush material",
            "/me", "List your personal schematics",
            "/middle", "Set the center block(s)",
            "/mine", "List your personal schematics",
            "/mirror", "Flip the contents of the clipboard across the origin",
            "/morph", "Morph brush, morphs blocks in the area",
            "/move", "Move the contents of the selection",
            "/mv", "Move the contents of the selection",
            "/naturalize", "3 layers of dirt on top then rock below",
            "/navwand", "Navigation wand tool",
            "/nbtinfo", "View nbt info for a block",
            "/near", "Find nearby edits",
            "/none", "Unbind a bound tool from your current item",
            "/ore", "Generates ores",
            "/ores", "Generates ores",
            "/outline", "Build the walls, ceiling, and floor of a selection",
            "/outset", "Outset the selection area",
            "/overlay", "Set a block on top of blocks in the region",
            "/p", "Paste the clipboard's contents",
            "/pa", "Paste the clipboard's contents",
            "/partition", "Creates random lines to break the terrain into pieces",
            "/paste", "Paste the clipboard's contents",
            "/pattern", "Set the brush material",
            "/perf", "Toggle side effects for performance",
            "/place", "Place the clipboard's contents without applying transformations (e.g. rotate)",
            "/placement", "Select which placement to use",
            "/popschem", "Scatter a schematic on a surface",
            "/populateschem", "Scatter a schematic on a surface",
            "/populateschematic", "Scatter a schematic on a surface",
            "/pos", "Set positions",
            "/pos1", "Set position 1",
            "/pos2", "Set position 2",
            "/preplace", "Replace all blocks in the selection with a pattern",
            "/primary", "Set the right click brush",
            "/private", "List your personal schematics",
            "/ps", "Scatter a schematic on a surface",
            "/pschem", "Scatter a schematic on a surface",
            "/public", "List public schematics",
            "/pull", "Pull terrain towards you",
            "/pumpkins", "Generate pumpkin patches",
            "/pyramid", "Generate a filled pyramid",
            "/r", "Set all connected blocks",
            "/raise", "Raise brush, raise all blocks by one",
            "/range", "Set the brush range",
            "/re", "Replace all blocks in the selection with another",
            "/rea", "Replace all blocks in the selection with another",
            "/reap", "Replace all blocks in the selection with another",
            "/recur", "Enable the recursive super pickaxe pickaxe mode",
            "/recurse", "Set all connected blocks",
            "/recursive", "Set all connected blocks",
            "/redo", "Redoes the last action (from history)",
            "/regen", "Regenerates the contents of the selection",
            "/registry", "Search through the given registry",
            "/reload", "Reload configuration and translations",
            "/rem", "Remove all entities of a type",
            "/remapall", "Remap the world between MCPE/PC values",
            "/rement", "Remove all entities of a type",
            "/remove", "Remove all entities of a type",
            "/removeabove", "Remove blocks above your head.",
            "/removebelow", "Remove blocks below you.",
            "/removelayers", "Removes matching chunk layers",
            "/removelighting", "Removing lighting in a selection",
            "/removenear", "Remove blocks near you.",
            "/reorder", "Sets the reorder mode of WorldEdit",
            "/rep", "Replace all blocks in the selection with another",
            "/repall", "Replace all blocks in the selection with another",
            "/repallpat", "Replace all blocks in the selection with another",
            "/repl", "Block replacer tool",
            "/replace", "Replace all blocks in the selection with another",
            "/replaceall", "Replace all blocks in the selection with another",
            "/replaceallpattern", "Replace all blocks in the selection with another",
            "/replacenear", "Replace nearby blocks",
            "/replacepattern", "Replace all blocks in the selection with a pattern",
            "/report", "Writes a report on WorldEdit",
            "/rerun", "Rerun edits",
            "/restore", "Rerun edits",
            "/rock", "Creates a distorted sphere",
            "/rollback", "Undo a specific edit. ",
            "/rotate", "Rotate the contents of the clipboard",
            "/rp", "Replace all blocks in the selection with a pattern",
            "/s", "Choose the sphere brush",
            "/saggedline", "Create a hanging line between two points",
            "/save", "Save your clipboard into a schematic file",
            "/savebrush", "Save your current brush",
            "/scatter", "Scatter a pattern on a surface",
            "/scattercmd", "Run commands at random points on a surface",
            "/scattercommand", "Run commands at random points on a surface",
            "/scmd", "Run commands at random points on a surface",
            "/scommand", "Run commands at random points on a surface",
            "/scroll", "Toggle between different target modes",
            "/search", "Find nearby edits",
            "/searchitem", "Search for an item",
            "/secondary", "Set the left click brush",
            "/sel", "Choose a region selector",
            "/select", "Select your current allowed region",
            "/selwand", "Selection wand tool",
            "/set", "Sets all the blocks in the region",
            "/setbiome", "Sets the biome of your current block or region.",
            "/setblocklight", "Set block lighting in a selection",
            "/setskylight", "Set sky lighting in a selection",
            "/share", "Share your clipboard as a schematic online",
            "/shatter", "Creates random lines to break the terrain into pieces",
            "/shift", "Shift the selection area",
            "/single", "Enable the single block super pickaxe mode",
            "/size", "Get information about the selection",
            "/smask", "Set the brush source mask",
            "/smooth", "Smooth the elevation in the selection",
            "/snow", "Snow brush, sets snow in the area",
            "/snowsmooth", "Smooth the elevation in the selection with snow layers",
            "/solve", "Evaluate a mathematical expression",
            "/sourcemask", "Set the brush source mask",
            "/sphere", "Generates a filled sphere.",
            "/spl", "Join multiple objects together in a curve",
            "/splat", "Choose the splatter brush",
            "/splatter", "Splatter a pattern on a surface",
            "/spline", "Join multiple objects together in a curve",
            "/split", "Creates random lines to break the terrain into pieces",
            "/sspl", "Draws a spline (curved line) on the surface",
            "/sspline", "Draws a spline (curved line) on the surface",
            "/stack", "Repeat the contents of the selection",
            "/stacker", "Block stacker tool",
            "/stencil", "Use a height map to paint a surface",
            "/structure", "Generate Minecraft structures",
            "/structureplacer", "Structure placer tool",
            "/structuretool", "Structure placer tool",
            "/summarize", "Summarize an edit",
            "/summary", "Summarize an edit",
            "/surf", "Use a height map to paint a surface",
            "/surface", "Use a height map to paint a surface",
            "/surfacespline", "Draws a spline (curved line) on the surface",
            "/sw", "Sweep your clipboard content along a curve",
            "/sweep", "Sweep your clipboard content along a curve",
            "/tar", "Toggle between different target modes",
            "/target", "Toggle between different target modes",
            "/targetmask", "Set the mask used to stop tool traces",
            "/targetoffset", "Set the targeting mask",
            "/tarmask", "Set the mask used to stop tool traces",
            "/test", "test region",
            "/thaw", "Thaws the area",
            "/threads", "Print all thread stacks",
            "/thru", "Pass through walls",
            "/timeout", "Modify evaluation timeout time.",
            "/tips", "Toggle FAWE tips",
            "/tm", "Set the mask used to stop tool traces",
            "/to", "Set the targeting mask",
            "/toggleeditwand", "Remind the user that the wand is now a tool and can be unbound with /tool none.",
            "/toggleplace", "Switch between your position and pos1 for placement",
            "/trace", "Toggles trace hook",
            "/tracemask", "Set the mask used to stop tool traces",
            "/transform", "Set the brush transform",
            "/transforms", "View help about transforms",
            "/tree", "Tree generator tool",
            "/trim", "Minimize the selection to encompass matching blocks",
            "/trimallair", "Trim all air in the world",
            "/trimallplots", "Trim chunks in a Plot World",
            "/tz", "Set your timezone for snapshots",
            "/undo", "Undoes the last action (from history)",
            "/unload", "Remove a clipboard from your multi-clipboard",
            "/unset", "Clear the chunks in a selection (delete without defrag)",
            "/unstuck", "Escape from being stuck inside a block",
            "/up", "Go upwards some distance",
            "/update", "Apply side effects to your selection",
            "/updateblocks", " 'Fixes ' all blocks in the region to the correct shape/connections based on surrounding blocks",
            "/use", "Choose a snapshot to use",
            "/vaesweep", "Sweep your clipboard content along a curve",
            "/ver", "Get the FAWE version",
            "/version", "Get the FAWE version",
            "/walls", "Build the four sides of the selection",
            "/wand", "Get the wand object",
            "/warwand", "Wand at a distance tool",
            "/watchdog", "Changes watchdog hook state.",
            "/wea", "Bypass region restrictions",
            "/weanywhere", "Bypass region restrictions",
            "/wer", "Select your current allowed region",
            "/world", "Sets the world override",
            "/worldeditanywhere", "Bypass region restrictions",
            "/worldeditregion", "Select your current allowed region",
    };

    static void register(CommandRegistry registry) {
        for (int i = 0; i + 1 < REMAINING.length; i += 2) {
            String name = REMAINING[i];
            if (registry.get(name) != null) {
                continue;
            }
            CommandRegistry.Entry entry = registry.register(name);
            entry.description = REMAINING[i + 1].isEmpty() ? "WorldEdit/FAWE command" : REMAINING[i + 1];
            entry.group = groupFor(name);
            entry.status = "stub";
            entry.handler = ctx -> ctx.actor().message(Msg.warn("'" + name
                    + "' is registered but its port is not finished in this build. See docs/COMMANDS.md."));
        }
        linkAliases(registry);
    }

    /**
     * Turns the stubs that are really aliases of a finished command into working
     * aliases.
     *
     * <p>{@link AliasTable} is generated from the WorldEdit/FAWE command
     * declarations, so the alias families are exact; the description check below
     * only catches the few names the inventory does not cover.</p>
     */
    private static void linkAliases(CommandRegistry registry) {
        for (int i = 0; i + 1 < AliasTable.PAIRS.length; i += 2) {
            CommandRegistry.Entry stub = registry.get(AliasTable.PAIRS[i]);
            CommandRegistry.Entry target = registry.get(AliasTable.PAIRS[i + 1]);
            if (stub == null || target == null || stub == target || !"stub".equals(stub.status)) {
                continue;
            }
            delegate(registry, stub, target);
        }
        for (CommandRegistry.Entry stub : registry.all()) {
            if (!"stub".equals(stub.status) || stub.description.isEmpty()) {
                continue;
            }
            for (CommandRegistry.Entry candidate : registry.all()) {
                if (candidate == stub || !"implemented".equals(candidate.status)
                        || !stub.description.equalsIgnoreCase(candidate.description)) {
                    continue;
                }
                delegate(registry, stub, candidate);
                break;
            }
        }
    }

    /** Wires {@code stub} to run {@code target} with the same arguments. */
    private static void delegate(CommandRegistry registry, CommandRegistry.Entry stub,
                                 CommandRegistry.Entry target) {
        stub.status = "alias";
        stub.group = target.group;
        stub.arguments.clear();
        stub.arguments.addAll(target.arguments);
        stub.booleanFlags.addAll(target.booleanFlags);
        stub.valueFlags.addAll(target.valueFlags);
        stub.handler = ctx -> {
            String arguments = ctx.joined(0);
            registry.dispatch(ctx.actor(), target.name + (arguments.isEmpty() ? "" : " " + arguments));
        };
    }

    /** Puts every stubbed command in the right help section. */
    private static String groupFor(String name) {
        String key = name.toLowerCase(java.util.Locale.ROOT).replaceFirst("^/+", "");
        if (key.startsWith("brush") || key.equals("br") || key.startsWith("br ")) {
            return "brush";
        }
        if (key.startsWith("schem") || key.startsWith("snap")) {
            return "schematic";
        }
        if (key.startsWith("tool") || key.startsWith("superpickaxe") || key.startsWith("sp")) {
            return "tool";
        }
        if (key.startsWith("biome")) {
            return "biome";
        }
        if (key.startsWith("chunk") || key.equals("lazycopy") || key.equals("lazycut")
                || key.startsWith("delchunks") || key.startsWith("trimall")) {
            return "chunk";
        }
        if (key.startsWith("nbt") || key.startsWith("nbtinfo")) {
            return "info";
        }
        if (key.startsWith("height") || key.startsWith("world") || key.startsWith("watchdog")
                || key.startsWith("timeout") || key.startsWith("limit") || key.startsWith("perf")
                || key.startsWith("threads") || key.startsWith("trace") || key.startsWith("debug")
                || key.startsWith("reload") || key.startsWith("version") || key.startsWith("ver")
                || key.startsWith("tz") || key.startsWith("confirm") || key.startsWith("report")) {
            return "utility";
        }
        if (key.startsWith("snapshot") || key.startsWith("restore") || key.startsWith("rollback")
                || key.startsWith("snap") || key.startsWith("use") || key.startsWith("before")
                || key.startsWith("after") || key.startsWith("list")) {
            return "snapshot";
        }
        if (key.startsWith("forest") || key.startsWith("flora") || key.startsWith("generat")
                || key.startsWith("gen") || key.startsWith("caves") || key.startsWith("pumpkin")
                || key.startsWith("ore") || key.startsWith("snow") || key.startsWith("fix")) {
            return "generation";
        }
        if (key.startsWith("copy") || key.startsWith("cut") || key.startsWith("paste")
                || key.startsWith("clipboard") || key.startsWith("clearclip") || key.startsWith("lazy")
                || key.startsWith("paste") || key.startsWith("rotate") || key.startsWith("flip")
                || key.startsWith("schem")) {
            return "clipboard";
        }
        if (key.startsWith("undo") || key.startsWith("redo") || key.startsWith("history")
                || key.startsWith("clearhistory")) {
            return "history";
        }
        if (key.startsWith("jumpto") || key.startsWith("thru") || key.startsWith("unstuck")
                || key.startsWith("ascend") || key.startsWith("descend") || key.startsWith("up")
                || key.startsWith("ceil") || key.startsWith("pos") || key.startsWith("hpos")
                || key.startsWith("farwand") || key.startsWith("navwand") || key.startsWith("target")) {
            return "navigation";
        }
        if (key.startsWith("mask") || key.startsWith("gmask") || key.startsWith("smask")
                || key.startsWith("sourcemask") || key.startsWith("tracemask") || key.startsWith("gmask")) {
            return "mask";
        }
        if (key.startsWith("pattern") || key.startsWith("gtexture") || key.startsWith("gtransform")
                || key.startsWith("transform") || key.startsWith("material") || key.startsWith("rep")) {
            return "pattern";
        }
        if (key.startsWith("distr") || key.startsWith("count") || key.startsWith("search")
                || key.startsWith("info") || key.startsWith("near") || key.startsWith("size")
                || key.startsWith("sel")) {
            return "info";
        }
        if (key.equals("help") || key.equals("we") || key.equals("/we")) {
            return "help";
        }
        return "worldedit";
    }
}
