package com.fawebutinmods.core.command;

/**
 * Command names that still have no implementation, generated by
 * {@code scripts/generate_command_tables.py}.
 *
 * <p>Every name WorldEdit 7.3.17 and FastAsyncWorldEdit declare is registered,
 * so nothing is missing from the command surface; this table holds the ones
 * that answer with a clear "not implemented" message. It shrinks on its own as
 * command classes take the names over.</p>
 *
 * <p>Do not edit by hand: re-run the script after changing the command set.</p>
 */
final class StubTable {

    private StubTable() {
    }

    /** {@code name, description} pairs. */
    static final String[] ENTRIES = {
    };
}
