package com.fawebutinmods.core.command;

/**
 * Alias routes generated by {@code scripts/generate_command_tables.py}.
 *
 * <p>WorldEdit declares a command once and gives it several spellings, and
 * declares brush, tool, schematic, snapshot and super-pickaxe sub-commands
 * inside their container. Each pair is {@code spelling}, {@code command}:
 * the spelling runs the command that already implements the behaviour, so no
 * duplicate implementation is needed for names such as {@code 0} ({@code /air})
 * or {@code blob} ({@code /brush rock}).</p>
 *
 * <p>Do not edit by hand: re-run the script after changing the command set.</p>
 */
final class SubCommandTable {

    private SubCommandTable() {
    }

    static final String[] PAIRS = {
            "middle", "//center",
            "mirror", "//flip",
            "mv", "//move",
            "pa", "//paste",
            "rep", "//replace",
            "biomels", "//biomelist",
            "listbiomes", "//biomelist",
            "cc", "//clearclipboard",
            "clearclip", "//clearclipboard",
            "/brush ex", "/brush extinguish",
            "ext", "//extinguish",
            "/brush r", "/brush recursive",
    };
}
