#!/usr/bin/env python3
"""Generates core/src/main/java/com/fawebutinmods/core/command/AliasTable.java.

WorldEdit and FastAsyncWorldEdit declare a command's aliases next to the
command itself. docs/commands-inventory.json is the machine-readable dump of
those declarations (one row per annotated method, with its name and aliases), so
every alias family is known exactly: this script folds the families into the
`alias -> canonical command` pairs the engine uses to make an alias stub
delegate to the command that is already implemented.

Usage:  python3 scripts/generate_alias_table.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parent.parent
INVENTORY = ROOT / "docs" / "commands-inventory.json"
SPEC = ROOT / "docs" / "commands-spec.json"
OUTPUT = ROOT / "core/src/main/java/com/fawebutinmods/core/command/AliasTable.java"


def normalise(name: str) -> str:
    name = name.strip()
    return name


def spellings(name: str) -> set[str]:
    """Every spelling of a command name the engine may hold."""
    name = normalise(name)
    out = {name}
    if name.startswith("//"):
        out.add("/" + name.lstrip("/"))
        out.add(name.lstrip("/"))
    elif name.startswith("/"):
        out.add("//" + name.lstrip("/"))
        out.add(name.lstrip("/"))
    else:
        out.add("/" + name)
        out.add("//" + name)
    return out


def main() -> None:
    inventory = json.loads(INVENTORY.read_text())
    spec = json.loads(SPEC.read_text())

    status = {normalise(c["name"]): c["status"] for c in spec["commands"]}
    # Every spelling of a registered command, mapped to that command's name.
    spelling_to_command: dict[str, str] = {}
    for command in spec["commands"]:
        for spelling in spellings(command["name"]):
            spelling_to_command.setdefault(spelling, command["name"])

    implemented: set[str] = {c["name"] for c in spec["commands"] if c["status"] == "implemented"}

    # Alias families: every annotated method is one command with its aliases.
    families: list[list[str]] = []
    for row in inventory:
        family = [row.get("name", "")] + list(row.get("aliases") or [])
        family = [f for f in (normalise(x) for x in family) if f and f not in {"*", "/", ".s"}]
        if family:
            families.append(family)

    pairs: dict[str, str] = {}
    for family in families:
        commands = []
        for spelling in family:
            command = spelling_to_command.get(spelling)
            if command and command not in commands:
                commands.append(command)
        if len(commands) < 2:
            continue
        target = next((c for c in commands if c in implemented), None)
        if target is None:
            continue
        for command in commands:
            if command != target and status.get(command) == "stub":
                pairs.setdefault(command, target)

    lines = [
        "package com.fawebutinmods.core.command;",
        "",
        "/**",
        " * Alias table generated by {@code scripts/generate_alias_table.py}.",
        " *",
        " * <p>Each pair is {@code alias}, {@code canonical command}: WorldEdit declares",
        " * aliases next to the command they belong to, so a stub that is really an alias",
        " * of a finished command is wired to it instead of staying a stub.</p>",
        " *",
        " * <p>Do not edit by hand: re-run the script after changing the command set.</p>",
        " */",
        "final class AliasTable {",
        "",
        "    private AliasTable() {",
        "    }",
        "",
        "    static final String[] PAIRS = {",
    ]
    for alias in sorted(pairs):
        lines.append(f'            "{alias}", "{pairs[alias]}",')
    lines += [
        "    };",
        "}",
        "",
    ]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(pairs)} alias pairs")


if __name__ == "__main__":
    main()
